### ISSUE TITLE
which samtools version should be used ?

### ISSUE THREAD

**Issue by samfux84** [jdaron/epiTEome#4]
In your installation instructions, you write:

samtools (version 1.3.1 or higher)

But you also write that

Bio::DB::Sam

is required.

Samtools 1.3.1 and higher neither install bam.h nor libbam.a, but these files are required by Bio::DB::Sam. Most people install Bio::DB::Sam only with samtools releases 0.1.x (the old versions that still come with bam.h and libbam.a).

This is very confusing.

**Comment by jdaron** [comment]
Hi Samfux84,

I agree this is confusing. I will try to fix as soon as possible.
Basically to install the bioperl lib Bio::DB::Sam you need to use an older version of samtools.

Sorry for the trouble it creates.
Josquin

**Comment by samfux84** [comment]
Hi jdaron,

Thank you for your fast reply. In my opinion it is the fault of the samtools developers, that created this confusion.

So would it work, to use epiteome with two different samtools versions ?

0.1.17 for Bio::DB::Sam

and

1.7 for epiteome ?

**Comment by jdaron** [comment]
Yes, as you mentioned, what I suggest you to do is to download both version of samtools, use 0.1.17 only to compile the Bio::DB::Sam and have samtools 1.7 in your path for epiTEome.

Sorry for this confusion, I will make it clears in the readme and if I have time improve the code.

**Comment by samfux84** [comment]
@jdaron: Thank you for your help, this solved the problem.
